language: cpp

os:
  - linux

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitPPCupdate.pl
  - export DEVKITPRO=$HOME/devkitPro
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC

install:
  - sudo perl devkitPPCupdate.pl

script:
  - make build