language: cpp
sudo: false

os:
  - linux

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

cache:
  directories:
    - ${DEVKITPRO}

before_install:
  - wget https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitPPCupdate.pl

install:
  - perl devkitPPCupdate.pl
  - ${DEVKITPPC}/bin/powerpc-eabi-gcc --version

script:
  - make build