language: c

os:
  - linux

before_install:
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitPPCupdate.pl

install:
  - sudo perl devkitPPCupdate.pl

script:
  - make build