language: cpp
dist: trusty
sudo: required

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

cache:
  directories:
    - ${DEVKITPRO}

before_install:
  - wget https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitPPCupdate.pl

install:
  - sudo perl devkitPPCupdate.pl
  - ${DEVKITPPC}/bin/powerpc-eabi-gcc --version

script:
  - make build