language: cpp
sudo: required

os:
  - linux

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

cache:
  directories:
    - ${DEVKITPRO}

before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb

install:
  - sudo dpkg --install devkitpro-pacman.deb
  - sudo dkp-pacman --sync --sysupgrade --refresh --needed --noconfirm wii-dev ppc-mxml ppc-libpng ppc-freetype ppc-libjpeg-turbo
  - ${DEVKITPPC}/bin/powerpc-eabi-gcc --version

script:
  - make build
