name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v4

    - name: Build application
      run: |
        /opt/devkitpro/portlibs/wii/bin/powerpc-eabi-cmake -B $GITHUB_WORKSPACE/build
        cmake --build $GITHUB_WORKSPACE/build -j $(nproc)

    - name: Move file
      run: mv build/Wii-Tac-Toe.dol Wii-Tac-Toe/boot.dol

    - uses: actions/upload-artifact@v4
      with:
        name: Wii-Tac-Toe
        path: Wii-Tac-Toe/
