name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v4

    - name: Build application
      run: |
        sh .devcontainer/post-create.sh
        /opt/devkitpro/portlibs/wii/bin/powerpc-eabi-cmake -B $GITHUB_WORKSPACE/build -G Ninja
        cmake --build $GITHUB_WORKSPACE/build --verbose

    - name: Prepare artifact
      run: |
        mkdir --parents --verbose /tmp/artifact/Wii-Tac-Toe
        mv --verbose build/Wii-Tac-Toe.dol /tmp/artifact/Wii-Tac-Toe/boot.dol
        cp --verbose Wii-Tac-Toe/* /tmp/artifact/Wii-Tac-Toe/

    - uses: actions/upload-artifact@v4
      with:
        name: Wii-Tac-Toe
        path: /tmp/artifact/
