name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v2

    - name: Download and install devkitPro
      run: |
        wget -nv https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.deb
        sudo dpkg --install devkitpro-pacman.deb

    - name: Install required packages
      run: sudo dkp-pacman --sync --sysupgrade --refresh --needed --noconfirm wii-dev ppc-mxml ppc-libpng ppc-freetype ppc-libjpeg-turbo

    - name: Build application
      env:
        DEVKITPRO: /opt/devkitpro
        DEVKITPPC: ${DEVKITPRO}/devkitPPC
      run: make build

    - name: Move file
      run: mv Wii-Tac-Toe.dol Wii-Tac-Toe/boot.dol

    - uses: actions/upload-artifact@master
      with:
        name: Wii-Tac-Toe
        path: Wii-Tac-Toe/
